### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by jwaltrip4** [troykelly/hassio-addons-letsencrypt-lexicon#45]
# Problem/Motivation
This has been running for a while.  Recently started failing.

## Expected behavior
It should not crash.  Sorry, not very good with Python

## Actual behavior

Crashes while getting certs

## Steps to reproduce
Run the addon

### Error
 + 1 pending challenge(s)
 + Deploying challenge tokens...
deploy_challenge called: <hidden>, Mne9D0gMvp6njr5S8VEA9YQ5aD0dGBqOsZkgkyk74a4, sDgPxD-vehVAj3iFtXEZWSNzojXcuqjHw_wmBo3kpoI
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/lexicon/_private/cli.py", line 135, in main
    results = client.execute()
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/lexicon/client.py", line 211, in execute
    executor = self.__enter__()
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/lexicon/client.py", line 168, in __enter__
    raise e
  File "/usr/local/lib/python3.12/site-packages/lexicon/client.py", line 161, in __enter__
    provider.authenticate()
  File "/usr/local/lib/python3.12/site-packages/lexicon/_private/providers/godaddy.py", line 62, in authenticate
    result = self._get(f"/domains/{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/lexicon/interfaces.py", line 162, in _get
    return self._request("GET", url, query_params=query_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/lexicon/_private/providers/godaddy.py", line 338, in _request
    result.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.godaddy.com/v1/domains/<hidden>.com
ERROR: deploy_challenge hook returned with non-zero exit code
[17:42:56] WARNING: certificate refresh crashed, halting add-on

**Comment by troykelly** [comment]
Hi there @jwaltrip4 thank you for reaching out.

Unfortunately, a few months ago, GoDaddy removed access to its API for users with less than 10 (or maybe 20 or maybe 50—it's not clear) domains.

There's a discussion here on [reddit](https://www.reddit.com/r/godaddy/comments/1bl0f5r/am_i_the_only_one_who_cant_use_the_api/).

While the removal of the API access is a challenge, there are options available. You can consider moving to a provider that supports an API or, if feasible, moving to an enterprise plan with GoDaddy. I understand that these options may not be ideal, and I'm sorry for the inconvenience.

**Comment by troykelly** [comment]
Closing this for now, let me know if you need anything else.
